### ISSUE TITLE
Creating subBranch on a new mainBranch

### ISSUE THREAD

**Issue by AndersGeer** [MummiSnow/DMExcercise1#1]
Creating subBranch on a new mainBranch creates the subBranch with a main branch, as the mainBranch as intended in not created. 

SubBranch is not supposed to be created either

<img width="1920" alt="screen_shot_2016-11-12_at_16 48 04" src="https://cloud.githubusercontent.com/assets/9446585/20239062/6506cd60-a8f8-11e6-92b7-a1f99ec09313.png">

**Comment by MummiSnow** [comment]
fixed with the latest commit 4c4a908
